version: '3.1'

services:
  app:
    image: 5eb1127fef05
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=root
      - DB_URL=jdbc:mysql://db:3306/mysql
    depends_on:
      - db
  db:
    image: 'mysql'
    container_name: db
    expose:
      - '3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
